openapi: 3.0.0
info:
  version: 0.0.1
  title: Time Machine API
  description: The API used for the Time Machine Project.
servers:
  - url: https://demo-timemachine.epfl.ch/api
tags:
  - name: Datasets
    description: Endpoints related to datasets
  - name: Points of Interest
    description: Endpoints related to points of interest (POI)
  - name: Observations
    description: Endpoints related to observations
  - name: Historical Records
    description: Endpoints related to historical records
  - name: Geometries
    description: Endpoints related to geometries
paths:
  /datasets:
    get:
      tags:
        - Datasets
      summary: List all datasets
      description: Retrieve a list of all datasets
      responses:
        "200":
          description: A list of datasets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DatasetsResponse"
              example:
                id: "https://demo-timemachine.epfl.ch/api/datasets?page=1"
                total: 2
                per_page: 100
                current_page: 1
                last_page: 1
                next: null
                previous: null
                items:
                  - uuid: "fb5761db-9b73-502b-bd4c-7a3f4516e911"
                    dataset_id: "VENICE_GARZONI"
                    rde_type: "dataset"
                    description: "TODO"
                    paradata: "TODO"
                    time_range:
                      - "1575-01-01"
                      - "1772-12-31"
                    configuration: "garzoni_ds_configuration.json"
                  - uuid: "29d8504f-52fc-56a3-b7b1-8960b2ebb1e0"
                    dataset_id: "VENICE_1808_SOMMARIONI"
                    rde_type: "dataset"
                    description: 'Digitisation of the 1808 Napoleonic cadaster of Venice. Contains both numeric facsimile of the cadatser map as well as their description in the written registry, called the "Sommarioni"'
                    paradata: "The textual data from the register was manually transcribed, then semi-automatically cleaned and normalized by various researchers. The maps were vetcorized into geometries through computer vision techniques and then manually corrected and expanded."
                    time_range:
                      - "1808-01-01"
                      - "1808-12-31"
                    configuration: "sommarioni_ds_configuration.json"
  /datasets/{uuid}:
    get:
      tags:
        - Datasets
      summary: Get a specific dataset
      description: Retrieve a specific dataset by its UUID
      parameters:
        - name: uuid
          in: path
          required: true
          description: The UUID of the dataset to retrieve
          schema:
            type: string
      responses:
        "200":
          description: The dataset details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dataset"
              example:
                uuid: "fb5761db-9b73-502b-bd4c-7a3f4516e911"
                dataset_id: "VENICE_GARZONI"
                rde_type: "dataset"
                description: "TODO"
                paradata: "TODO"
                time_range:
                  - "1575-01-01"
                  - "1772-12-31"
                configuration: "garzoni_ds_configuration.json"
        "404":
          description: Dataset not found
  /poi:
    get:
      tags:
        - Points of Interest
      summary: List all points of interest
      description: Retrieve a list of all points of interest (POI)
      responses:
        "200":
          description: A list of points of interest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/POIResponse"
              example:
                id: "https://demo-timemachine.epfl.ch/api/poi?page=1"
                total: 5516
                per_page: 100
                current_page: 1
                last_page: 56
                next: "https://demo-timemachine.epfl.ch/api/poi?page=2"
                previous: null
                items:
                  - type: "Feature"
                    properties:
                      uuid: "00157e17-e67e-5975-acd7-669196d84dc1"
                      rde_type: "poi"
                      time_range:
                        - "1575-07-07"
                        - "1575-07-07"
                      contains:
                        - "db0b400f-3baf-5d85-b4ac-db620918b0a2"
                    geometry:
                      type: "Point"
                      coordinates:
                        - 12.33372
                        - 45.43573
                  - type: "Feature"
                    properties:
                      uuid: "0019a276-f4e9-5c5e-8a31-1e15cd8414ec"
                      rde_type: "poi"
                      time_range:
                        - "1594-02-06"
                        - "1594-02-06"
                      contains:
                        - "332810c2-423a-538d-8568-50e72528ee07"
                    geometry:
                      type: "Point"
                      coordinates:
                        - 12.3267
                        - 45.4434
  /poi/{uuid}:
    get:
      tags:
        - Points of Interest
      summary: Get a specific point of interest
      description: Retrieve a specific point of interest by its UUID
      parameters:
        - name: uuid
          in: path
          required: true
          description: The UUID of the point of interest to retrieve
          schema:
            type: string
      responses:
        "200":
          description: The point of interest details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/POI"
              example:
                type: "Feature"
                properties:
                  uuid: "00157e17-e67e-5975-acd7-669196d84dc1"
                  rde_type: "poi"
                  time_range:
                    - "1575-07-07"
                    - "1575-07-07"
                  contains:
                    - "db0b400f-3baf-5d85-b4ac-db620918b0a2"
                geometry:
                  type: "Point"
                  coordinates:
                    - 12.33372
                    - 45.43573
        "404":
          description: Point of interest not found
  /poi/geojson:
    get:
      tags:
        - Points of Interest
      summary: Fetch POIs based on their position
      description: Retrieve points of interest within a specified bounding box (bbox)
      parameters:
        - name: bbox
          in: query
          required: true
          description: Bounding box to filter the points of interest, formatted as `minLon,minLat,maxLon,maxLat`
          schema:
            type: string
            example: "12.334753,45.436846,12.342332,45.433338"
      responses:
        "200":
          description: A collection of points of interest within the specified bbox
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/POIFeatureCollection"
              example:
                type: "FeatureCollection"
                crs:
                  type: "name"
                  properties:
                    name: "urn:ogc:def:crs:OGC:1.3:CRS84"
                features:
                  - type: "Feature"
                    properties:
                      uuid: "32f348cb-a4a3-543f-b026-6d25f75e3358"
                      rde_type: "poi"
                      time_range:
                        - "1620-07-15"
                        - "1620-07-15"
                      contains:
                        - "bf4b5d08-b9b0-5710-827c-229dae95d5d7"
                    geometry:
                      type: "Point"
                      coordinates:
                        - 12.337151
                        - 45.433645
                  - type: "Feature"
                    properties:
                      uuid: "35f76aff-f9a4-5a87-8241-dc8b64d19fb7"
                      rde_type: "poi"
                      time_range:
                        - "1621-01-10"
                        - "1621-01-10"
                      contains:
                        - "6db108c1-b89b-518a-8f73-3a166c9fa1a9"
                    geometry:
                      type: "Point"
                      coordinates:
                        - 12.337151
                        - 45.433645
                  - type: "Feature"
                    properties:
                      uuid: "516a9566-2a36-5749-83ac-ad7e08ef84cc"
                      rde_type: "poi"
                      time_range:
                        - "1606-07-24"
                        - "1606-07-24"
                      contains:
                        - "0ad48718-f0cf-5d7d-96de-653b575f2572"
                    geometry:
                      type: "Point"
                      coordinates:
                        - 12.337151
                        - 45.433645
  /obs:
    get:
      tags:
        - Observations
      summary: List all observations
      description: Retrieve a list of all observations
      responses:
        "200":
          description: A list of observations
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ObservationsResponse"
              example:
                id: "https://demo-timemachine.epfl.ch/api/obs?page=1"
                total: 5516
                per_page: 100
                current_page: 1
                last_page: 56
                next: "https://demo-timemachine.epfl.ch/api/obs?page=2"
                previous: null
                items:
                  - type: "Feature"
                    properties:
                      uuid: "c611232c-291a-5962-9d8d-f56745271b73"
                      dataset_id: "VENICE_GARZONI"
                      dataset_uuid: "fb5761db-9b73-502b-bd4c-7a3f4516e911"
                      rde_type: "obs"
                      type: "event"
                      time_range:
                        - "1575-01-02"
                        - "1575-01-02"
                      has_spatial_projection:
                        - "bfdf411d-cafe-531d-b8ce-fd8a12ab7c27"
                      documented_in:
                        - "394a376b-2075-5039-a6dc-f5f2c322bc5e"
                      part_of:
                        - "4bb39b4c-7e2a-5e1f-b178-a917ac35eeef"
                    geometry:
                      type: "Point"
                      coordinates:
                        - 12.3334
                        - 45.44178
                  - type: "Feature"
                    properties:
                      uuid: "f3c772c9-03ae-5d10-bde9-5631ae783d22"
                      dataset_id: "VENICE_GARZONI"
                      dataset_uuid: "fb5761db-9b73-502b-bd4c-7a3f4516e911"
                      rde_type: "obs"
                      type: "event"
                      time_range:
                        - "1575-01-02"
                        - "1575-01-02"
                      has_spatial_projection:
                        - "2a1f5629-e690-5197-ae2d-6a2205dc2dbe"
                      documented_in:
                        - "9034d850-7137-55bc-afce-7c9dfe7ca197"
                      part_of:
                        - "4c9b1d3e-de76-5259-ab69-db12b06dc9ed"
                    geometry:
                      type: "Point"
                      coordinates:
                        - 12.33219
                        - 45.44296
  /obs/{uuid}:
    get:
      tags:
        - Observations
      summary: Get a specific observation
      description: Retrieve a specific observation by its UUID
      parameters:
        - name: uuid
          in: path
          required: true
          description: The UUID of the observation to retrieve
          schema:
            type: string
      responses:
        "200":
          description: The observation details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Observation"
              example:
                type: "Feature"
                properties:
                  uuid: "db0b400f-3baf-5d85-b4ac-db620918b0a2"
                  dataset_id: "VENICE_GARZONI"
                  dataset_uuid: "fb5761db-9b73-502b-bd4c-7a3f4516e911"
                  rde_type: "obs"
                  type: "event"
                  time_range:
                    - "1575-07-07"
                    - "1575-07-07"
                  has_spatial_projection:
                    - "8761d309-e2aa-5f3a-bbe0-77ffbf0216e4"
                  documented_in:
                    - "87783dd8-3a62-5956-bf98-e369370c86cd"
                  part_of:
                    - "00157e17-e67e-5975-acd7-669196d84dc1"
                geometry:
                  type: "Point"
                  coordinates:
                    - 12.33372
                    - 45.43573
        "404":
          description: Observation not found
  /hr:
    get:
      tags:
        - Historical Records
      summary: List all historical records
      description: Retrieve a list of all historical records
      responses:
        "200":
          description: A list of historical records
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HistoricalRecordsResponse"
              example:
                id: "https://demo-timemachine.epfl.ch/api/hr?page=1"
                total: 62213
                per_page: 100
                current_page: 1
                last_page: 623
                next: "https://demo-timemachine.epfl.ch/api/hr?page=2"
                previous: null
                items:
                  - uuid: "2d351b23-3474-5bcf-8d4c-30cfec8862d7"
                    dataset_id: "711a79f7-b7d5-59b4-8dec-49f7857c1525"
                    rde_type: "hr"
                    type: "apprenticeship"
                    time_range:
                      - "1740-01-01"
                      - "1740-12-31"
                    paradata: "m"
                    documents:
                      - "f158d140-3c0e-517a-8d51-625f3e996ce7"
                    metadata:
                      owner_name: "Liberal Campi secondo prete titolato della Chiesa"
                      owner_code: "PPL"
                      owner_count: 1
                      owner_count_remark: ""
                      owner_entity: ""
                      owner_entity_group: ""
                      owner_first_name: "Liberal"
                      owner_family_name: "CAMPI"
                      owner_family_group: "CAMPI"
                      owner_title: "SECONDO PRETE TITOLATO DELLA CHIESA"
                      owner_title_std: "SECONDO PRETE"
                      owner_mestiere: ""
                      owner_mestiere_std: ""
                      ten_name: "Francesco Zeni"
                      function: "casa e bottega da barbier"
                      an_rendi: 70
                      id_napo: 3052
                      quantity_income: "nan"
                      quality_income: "nan"
                      author: "Davide"
                      place: "Campo vicino alla Chiesa"
                      parish: "San Cancian"
                      sestiere: "CN"
                      uid: "CNC-0001"
                      path_img: "436_Cannaregio/11_SCancian/SCancian_0_1.png"
                  - uuid: "ef792e67-9bbe-5e47-a5f6-b80040f6e813"
                    dataset_id: "711a79f7-b7d5-59b4-8dec-49f7857c1525"
                    rde_type: "hr"
                    type: "apprenticeship"
                    time_range:
                      - "1740-01-01"
                      - "1740-12-31"
                    paradata: "m"
                    documents:
                      - "58b7e89b-068e-539b-9aba-7f30eedea300"
                    metadata:
                      owner_name: "Filippo Frari terzo prete titolato della Chiesa"
                      owner_code: "PPL"
                      owner_count: 1
                      owner_count_remark: ""
                      owner_entity: ""
                      owner_entity_group: ""
                      owner_first_name: "Filippo"
                      owner_family_name: "FRARI"
                      owner_family_group: "FRARI"
                      owner_title: "TERZO PRETE TITOLATO DELLA CHIESA"
                      owner_title_std: "TERZO PRETE"
                      owner_mestiere: ""
                      owner_mestiere_std: ""
                      ten_name: "Dio M'aiuti Lazara"
                      function: "casa"
                      an_rendi: 60
                      id_napo: 3051
                      quantity_income: "nan"
                      quality_income: "nan"
                      author: "Davide"
                      place: "Campo vicino alla Chiesa"
                      parish: "San Cancian"
                      sestiere: "CN"
                      uid: "CNC-0002"
                      path_img: "436_Cannaregio/11_SCancian/SCancian_0_1.png"
                  - uuid: "5097edc6-ebc9-5b2f-8203-a256732a38f7"
                    dataset_id: "711a79f7-b7d5-59b4-8dec-49f7857c1525"
                    rde_type: "hr"
                    type: "apprenticeship"
                    time_range:
                      - "1740-01-01"
                      - "1740-12-31"
                    paradata: "m"
                    documents:
                      - "e5a0094f-ff37-5c82-9c18-98b65bf0f404"
                    metadata:
                      owner_name: "Pievan di San Cancian"
                      owner_code: "ent_REL_TTL"
                      owner_count: 1
                      owner_count_remark: ""
                      owner_entity: "PIEVAN DI SAN CANCIAN"
                      owner_entity_group: "CHIESA DI SAN CANCIANO"
                      owner_first_name: ""
                      owner_family_name: ""
                      owner_family_group: ""
                      owner_title: "pievan di san cancian"
                      owner_title_std: "PIEVANO"
                      owner_mestiere: ""
                      owner_mestiere_std: ""
                      ten_name: "Bortolamio Piazza"
                      function: "bottega da strazariol"
                      an_rendi: 14
                      id_napo: "nan"
                      quantity_income: "nan"
                      quality_income: "nan"
                      author: "Davide"
                      place: "Campo vicino alla Chiesa"
                      parish: "San Cancian"
                      sestiere: "CN"
                      uid: "CNC-0003"
                      path_img: "436_Cannaregio/11_SCancian/SCancian_0_1.png"
  /hr/{uuid}:
    get:
      tags:
        - Historical Records
      summary: Get a specific historical record
      description: Retrieve a specific historical record by its UUID
      parameters:
        - name: uuid
          in: path
          required: true
          description: The UUID of the historical record to retrieve
          schema:
            type: string
      responses:
        "200":
          description: The historical record details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HistoricalRecord"
              example:
                uuid: "2d351b23-3474-5bcf-8d4c-30cfec8862d7"
                dataset_id: "711a79f7-b7d5-59b4-8dec-49f7857c1525"
                rde_type: "hr"
                type: "apprenticeship"
                time_range:
                  - "1740-01-01"
                  - "1740-12-31"
                paradata: "m"
                documents:
                  - "f158d140-3c0e-517a-8d51-625f3e996ce7"
                metadata:
                  owner_name: "Liberal Campi secondo prete titolato della Chiesa"
                  owner_code: "PPL"
                  owner_count: 1
                  owner_count_remark: ""
                  owner_entity: ""
                  owner_entity_group: ""
                  owner_first_name: "Liberal"
                  owner_family_name: "CAMPI"
                  owner_family_group: "CAMPI"
                  owner_title: "SECONDO PRETE TITOLATO DELLA CHIESA"
                  owner_title_std: "SECONDO PRETE"
                  owner_mestiere: ""
                  owner_mestiere_std: ""
                  ten_name: "Francesco Zeni"
                  function: "casa e bottega da barbier"
                  an_rendi: 70
                  id_napo: 3052
                  quantity_income: "nan"
                  quality_income: "nan"
                  author: "Davide"
                  place: "Campo vicino alla Chiesa"
                  parish: "San Cancian"
                  sestiere: "CN"
                  uid: "CNC-0001"
                  path_img: "436_Cannaregio/11_SCancian/SCancian_0_1.png"
        "404":
          description: Historical record not found
  /geometries:
    get:
      tags:
        - Geometries
      summary: List all geometries
      description: Retrieve a list of all geometries
      responses:
        "200":
          description: A list of geometries
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeometriesResponse"
              example:
                id: "https://demo-timemachine.epfl.ch/api/geometries?page=1"
                total: 24506
                per_page: 100
                current_page: 1
                last_page: 246
                next: "https://demo-timemachine.epfl.ch/api/geometries?page=2"
                previous: null
                items:
                  - type: "Feature"
                    properties:
                      uuid: "48901e4e-5814-5933-875b-662da8372e7b"
                      map_id: "VENICE_1740_PARISH_MAP"
                      rde_type: "geometry"
                      time_range:
                        - "1575-01-01"
                        - "1772-12-31"
                    geometry:
                      type: "Polygon"
                      coordinates:
                        - [
                            [1371976.5745785462, 5691731.290402323],
                            [1372021.3200345468, 5691699.960656367],
                            [1372085.9354519886, 5691762.27825365],
                            [1372102.8796899803, 5691773.033982799],
                            [1372147.516462301, 5691791.828142474],
                            [1372169.866761354, 5691811.0842214],
                            [1372163.1845402282, 5691834.440871406],
                            [1372183.8516300349, 5691848.227823359],
                            [1372158.1458142607, 5691891.901186975],
                            [1372133.0884930505, 5691922.260665317],
                            [1372133.087020524, 5691922.260399587],
                            [1372115.7736807184, 5691932.218583229],
                            [1372075.4344623205, 5691916.574836529],
                            [1372061.6560155072, 5691867.400597848],
                            [1372067.7178286265, 5691854.417703299],
                            [1372011.1779420741, 5691780.110506882],
                            [1371976.5745785462, 5691731.290402323],
                          ]
                  - type: "Feature"
                    properties:
                      uuid: "d8b87e62-d6da-53f6-962e-1ea9c5310503"
                      map_id: "VENICE_1740_PARISH_MAP"
                      rde_type: "geometry"
                      time_range:
                        - "1575-01-01"
                        - "1772-12-31"
                    geometry:
                      type: "Polygon"
                      coordinates:
                        - [
                            [1372133.087756787, 5691922.260532453],
                            [1372171.9903204797, 5691995.190092289],
                            [1372313.4133413658, 5691947.112574518],
                            [1372285.2231295533, 5691879.844296886],
                            [1372279.254557911, 5691866.3974880455],
                            [1372269.0183286022, 5691856.0881435815],
                            [1372242.7523837825, 5691838.570505305],
                            [1372242.7509113597, 5691838.570239575],
                            [1372193.6392061901, 5691821.395300667],
                            [1372183.8523662712, 5691848.227956227],
                            [1372158.1465505103, 5691891.9013198465],
                            [1372133.087756787, 5691922.260532453],
                          ]
  /geometries/{uuid}:
    get:
      tags:
        - Geometries
      summary: Get a specific geometry
      description: Retrieve a specific geometry by its UUID
      parameters:
        - name: uuid
          in: path
          required: true
          description: The UUID of the geometry to retrieve
          schema:
            type: string
      responses:
        "200":
          description: The geometry details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Geometry"
              example:
                type: "Feature"
                properties:
                  uuid: "48901e4e-5814-5933-875b-662da8372e7b"
                  map_id: "VENICE_1740_PARISH_MAP"
                  rde_type: "geometry"
                  time_range:
                    - "1575-01-01"
                    - "1772-12-31"
                geometry:
                  type: "Polygon"
                  coordinates:
                    - [
                        [1371976.5745785462, 5691731.290402323],
                        [1372021.3200345468, 5691699.960656367],
                        [1372085.9354519886, 5691762.27825365],
                        [1372102.8796899803, 5691773.033982799],
                        [1372147.516462301, 5691791.828142474],
                        [1372169.866761354, 5691811.0842214],
                        [1372163.1845402282, 5691834.440871406],
                        [1372183.8516300349, 5691848.227823359],
                        [1372158.1458142607, 5691891.901186975],
                        [1372133.0884930505, 5691922.260665317],
                        [1372133.087020524, 5691922.260399587],
                        [1372115.7736807184, 5691932.218583229],
                        [1372075.4344623205, 5691916.574836529],
                        [1372061.6560155072, 5691867.400597848],
                        [1372067.7178286265, 5691854.417703299],
                        [1372011.1779420741, 5691780.110506882],
                        [1371976.5745785462, 5691731.290402323],
                      ]
        "404":
          description: Geometry not found
components:
  schemas:
    Dataset:
      type: object
      properties:
        uuid:
          type: string
          example: "fb5761db-9b73-502b-bd4c-7a3f4516e911"
        dataset_id:
          type: string
          example: "VENICE_GARZONI"
        rde_type:
          type: string
          example: "dataset"
        description:
          type: string
          example: "TODO"
        paradata:
          type: string
          example: "TODO"
        time_range:
          type: array
          items:
            type: string
            format: date
            example: "1575-01-01"
        configuration:
          type: string
          example: "garzoni_ds_configuration.json"
    DatasetsResponse:
      type: object
      properties:
        id:
          type: string
          example: "https://demo-timemachine.epfl.ch/api/datasets?page=1"
        total:
          type: integer
          example: 2
        per_page:
          type: integer
          example: 100
        current_page:
          type: integer
          example: 1
        last_page:
          type: integer
          example: 1
        next:
          type: string
          nullable: true
          example: null
        previous:
          type: string
          nullable: true
          example: null
        items:
          type: array
          items:
            $ref: "#/components/schemas/Dataset"
    POI:
      type: object
      properties:
        type:
          type: string
          example: "Feature"
        properties:
          type: object
          properties:
            uuid:
              type: string
              example: "00157e17-e67e-5975-acd7-669196d84dc1"
            rde_type:
              type: string
              example: "poi"
            time_range:
              type: array
              items:
                type: string
                format: date
                example: "1575-07-07"
            contains:
              type: array
              items:
                type: string
                example: "db0b400f-3baf-5d85-b4ac-db620918b0a2"
        geometry:
          type: object
          properties:
            type:
              type: string
              example: "Point"
            coordinates:
              type: array
              items:
                type: number
                example: 12.33372
    POIResponse:
      type: object
      properties:
        id:
          type: string
          example: "https://demo-timemachine.epfl.ch/api/poi?page=1"
        total:
          type: integer
          example: 5516
        per_page:
          type: integer
          example: 100
        current_page:
          type: integer
          example: 1
        last_page:
          type: integer
          example: 56
        next:
          type: string
          nullable: true
          example: "https://demo-timemachine.epfl.ch/api/poi?page=2"
        previous:
          type: string
          nullable: true
          example: null
        items:
          type: array
          items:
            $ref: "#/components/schemas/POI"
    POIFeature:
      type: object
      properties:
        type:
          type: string
          example: "Feature"
        properties:
          type: object
          properties:
            uuid:
              type: string
              example: "32f348cb-a4a3-543f-b026-6d25f75e3358"
            rde_type:
              type: string
              example: "poi"
            time_range:
              type: array
              items:
                type: string
                format: date
                example: "1620-07-15"
            contains:
              type: array
              items:
                type: string
                example: "bf4b5d08-b9b0-5710-827c-229dae95d5d7"
        geometry:
          type: object
          properties:
            type:
              type: string
              example: "Point"
            coordinates:
              type: array
              items:
                type: number
                example: 12.337151
    POIFeatureCollection:
      type: object
      properties:
        type:
          type: string
          example: "FeatureCollection"
        crs:
          type: object
          properties:
            type:
              type: string
              example: "name"
            properties:
              type: object
              properties:
                name:
                  type: string
                  example: "urn:ogc:def:crs:OGC:1.3:CRS84"
        features:
          type: array
          items:
            $ref: "#/components/schemas/POIFeature"
    Observation:
      type: object
      properties:
        type:
          type: string
          example: "Feature"
        properties:
          type: object
          properties:
            uuid:
              type: string
              example: "db0b400f-3baf-5d85-b4ac-db620918b0a2"
            dataset_id:
              type: string
              example: "VENICE_GARZONI"
            dataset_uuid:
              type: string
              example: "fb5761db-9b73-502b-bd4c-7a3f4516e911"
            rde_type:
              type: string
              example: "obs"
            type:
              type: string
              example: "event"
            time_range:
              type: array
              items:
                type: string
                format: date
                example: "1575-07-07"
            has_spatial_projection:
              type: array
              items:
                type: string
                example: "8761d309-e2aa-5f3a-bbe0-77ffbf0216e4"
            documented_in:
              type: array
              items:
                type: string
                example: "87783dd8-3a62-5956-bf98-e369370c86cd"
            part_of:
              type: array
              items:
                type: string
                example: "00157e17-e67e-5975-acd7-669196d84dc1"
        geometry:
          type: object
          properties:
            type:
              type: string
              example: "Point"
            coordinates:
              type: array
              items:
                type: number
                example: 12.33372
    ObservationsResponse:
      type: object
      properties:
        id:
          type: string
          example: "https://demo-timemachine.epfl.ch/api/obs?page=1"
        total:
          type: integer
          example: 5516
        per_page:
          type: integer
          example: 100
        current_page:
          type: integer
          example: 1
        last_page:
          type: integer
          example: 56
        next:
          type: string
          nullable: true
          example: "https://demo-timemachine.epfl.ch/api/obs?page=2"
        previous:
          type: string
          nullable: true
          example: null
        items:
          type: array
          items:
            $ref: "#/components/schemas/Observation"
    HistoricalRecord:
      type: object
      properties:
        uuid:
          type: string
          example: "2d351b23-3474-5bcf-8d4c-30cfec8862d7"
        dataset_id:
          type: string
          example: "711a79f7-b7d5-59b4-8dec-49f7857c1525"
        rde_type:
          type: string
          example: "hr"
        type:
          type: string
          example: "apprenticeship"
        time_range:
          type: array
          items:
            type: string
            format: date
            example: "1740-01-01"
        paradata:
          type: string
          example: "m"
        documents:
          type: array
          items:
            type: string
            example: "f158d140-3c0e-517a-8d51-625f3e996ce7"
        metadata:
          type: object
          properties:
            owner_name:
              type: string
              example: "Liberal Campi secondo prete titolato della Chiesa"
            owner_code:
              type: string
              example: "PPL"
            owner_count:
              type: integer
              example: 1
            owner_count_remark:
              type: string
              example: ""
            owner_entity:
              type: string
              example: ""
            owner_entity_group:
              type: string
              example: ""
            owner_first_name:
              type: string
              example: "Liberal"
            owner_family_name:
              type: string
              example: "CAMPI"
            owner_family_group:
              type: string
              example: "CAMPI"
            owner_title:
              type: string
              example: "SECONDO PRETE TITOLATO DELLA CHIESA"
            owner_title_std:
              type: string
              example: "SECONDO PRETE"
            owner_mestiere:
              type: string
              example: ""
            owner_mestiere_std:
              type: string
              example: ""
            ten_name:
              type: string
              example: "Francesco Zeni"
            function:
              type: string
              example: "casa e bottega da barbier"
            an_rendi:
              type: integer
              example: 70
            id_napo:
              type: integer
              example: 3052
            quantity_income:
              type: string
              example: "nan"
            quality_income:
              type: string
              example: "nan"
            author:
              type: string
              example: "Davide"
            place:
              type: string
              example: "Campo vicino alla Chiesa"
            parish:
              type: string
              example: "San Cancian"
            sestiere:
              type: string
              example: "CN"
            uid:
              type: string
              example: "CNC-0001"
            path_img:
              type: string
              example: "436_Cannaregio/11_SCancian/SCancian_0_1.png"
    HistoricalRecordsResponse:
      type: object
      properties:
        id:
          type: string
          example: "https://demo-timemachine.epfl.ch/api/hr?page=1"
        total:
          type: integer
          example: 62213
        per_page:
          type: integer
          example: 100
        current_page:
          type: integer
          example: 1
        last_page:
          type: integer
          example: 623
        next:
          type: string
          nullable: true
          example: "https://demo-timemachine.epfl.ch/api/hr?page=2"
        previous:
          type: string
          nullable: true
          example: null
        items:
          type: array
          items:
            $ref: "#/components/schemas/HistoricalRecord"
    Geometry:
      type: object
      properties:
        type:
          type: string
          example: "Feature"
        properties:
          type: object
          properties:
            uuid:
              type: string
              example: "48901e4e-5814-5933-875b-662da8372e7b"
            map_id:
              type: string
              example: "VENICE_1740_PARISH_MAP"
            rde_type:
              type: string
              example: "geometry"
            time_range:
              type: array
              items:
                type: string
                format: date
                example: "1575-01-01"
        geometry:
          type: object
          properties:
            type:
              type: string
              example: "Polygon"
            coordinates:
              type: array
              items:
                type: array
                items:
                  type: array
                  items:
                    type: number
                    example: 1371976.5745785462
    GeometriesResponse:
      type: object
      properties:
        id:
          type: string
          example: "https://demo-timemachine.epfl.ch/api/geometries?page=1"
        total:
          type: integer
          example: 24506
        per_page:
          type: integer
          example: 100
        current_page:
          type: integer
          example: 1
        last_page:
          type: integer
          example: 246
        next:
          type: string
          nullable: true
          example: "https://demo-timemachine.epfl.ch/api/geometries?page=2"
        previous:
          type: string
          nullable: true
          example: null
        items:
          type: array
          items:
            $ref: "#/components/schemas/Geometry"
